# name, desc required, author optional
name: "hello_world"
description: "hello world"
author: "avinash"


# it cannot have JOBs
# jobs:
#   first_job:

#     runs-on: ubuntu-latest

#     steps:
#       - name: prints hello
#         run: echo Hello World


inputs:
  message:  # 1st input var
    required: true
    description: message to print

  git_pat:  # 1st input var
    required: true
    description: git pat

runs:
  using: "composite"  # type  is composite

  steps:
    - name: prints hello
      shell: bash
      run: echo "Hello ${{ inputs.message }}"  # note how the input var is parametrized here

    - name: merge the code
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote add src https://github.com/aviram2308/branch_merge.git
        git fetch src
        git checkout master
        git merge src/master --allow-unrelated-histories
        ls -la
        echo git remote add tgt https://${{ inputs.git_pat }}@github.com/aviram2308/actions_test.git
        git remote add tgt https://${{ inputs.git_pat }}@github.com/aviram2308/actions_test.git
        # git remote get-url origin
        # git remote get-url src
        # git remote get-url tgt
        git push tgt master --force