name: "sync_cross_repo"
description: "sync cross repo"
author: "avinash"


inputs:
  git_pat: 
    required: true
    description: git pat

  src_repo: 
    required: true
    description: src_repo

  src_branch: 
    required: true
    description: src_branch

  tgt_repo: 
    required: true
    description: tgt_repo

  tgt_branch: 
    required: true
    description: tgt_branch

  github_account_name: 
    required: true
    description: github_account_name


runs:
  using: "composite"

  steps:
    - name: Set GitHub Bots as Authors
      shell: bash
      working-directory: ./temp_repo_dir
      run: |
        echo "Setting GitHub Bots as Authors"
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Creating a empty repo in the temp dir
      shell: bash
      working-directory: ./temp_repo_dir
      run: |
        echo "Creating a empty repo in the temp dir"
        git clone https://github.com/${{ inputs.github_account_name }}/${{ inputs.tgt_repo }}.git
        ls -la  

    - name: Add the SRC repo URL & Fetch it
      shell: bash
      working-directory: ./temp_repo_dir
      run: |
        echo "Adding the SRC repo URL & Fetching it"
        git remote add src https://github.com/${{ inputs.github_account_name }}/${{ inputs.src_repo }}.git
        git fetch src
        ls -la  

    - name: Merge SRC branch with CURRENT(TGT) branch
      shell: bash
      working-directory: ./temp_repo_dir
      run: |
        echo "Merging SRC branch with CURRENT(TGT) branch"
        git checkout ${{ inputs.tgt_branch }}
        git merge src/${{ inputs.src_branch }} --allow-unrelated-histories
        ls -la

    # - name: Add the TGT repo URL & Fetch it
    #   shell: bash
    #   working-directory: ./temp_repo_dir
    #   run: |
    #     git remote add tgt https://github.com/${{ inputs.github_account_name }}/${{ inputs.tgt_repo }}.git
    #     git fetch tgt
    #     ls -la  

    # - name: Merge TGT branch with SRC branch
    #   shell: bash
    #   working-directory: ./temp_repo_dir
    #   run: |
    #     git checkout ${{ inputs.src_branch }}
    #     git merge tgt/${{ inputs.tgt_branch }} --allow-unrelated-histories
    #     ls -la

    - name: Add CURRENT(TGT) repo PAT URL & Push it
      shell: bash
      working-directory: ./temp_repo_dir
      run: |
        echo "Adding CURRENT(TGT) repo PAT URL & Pushing it"
        git remote add tgt https://${{ inputs.git_pat }}@github.com/${{ inputs.github_account_name }}/${{ inputs.tgt_repo }}.git
        # git push tgt ${{ inputs.tgt_branch }} --force

        