name: "sync_cross_repo"
description: "sync cross repo"
author: "avinash"


inputs:
  git_pat: 
    required: true
    description: git pat

  src_repo: 
    required: true
    description: src_repo

  src_branch: 
    required: true
    description: src_branch

  tgt_repo: 
    required: true
    description: tgt_repo

  tgt_branch: 
    required: true
    description: tgt_branch

  github_account_name: 
    required: true
    description: github_account_name


runs:
  using: "composite"

  steps:
    - name: Set GitHub Bots as Authors
      shell: bash
      working-directory: ./temp_repo_dir
      run: |
        echo "Setting GitHub Bots as Authors"
        echo "Current working directory: $(pwd)"
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote -v

    - name: Cloning the TGT repo in temp dir
      shell: bash
      working-directory: ./temp_repo_dir
      run: |
        echo "Cloning the TGT repo in temp dir"
        echo "Current working directory: $(pwd)"
        git clone https://${{ inputs.git_pat }}@github.com/${{ inputs.github_account_name }}/${{ inputs.tgt_repo }}.git
        ls -la  
        git remote -v

    - name: Add the SRC repo URL & Fetch it
      shell: bash
      working-directory: ./temp_repo_dir/${{ inputs.tgt_repo }}
      run: |
        echo "Adding the SRC repo URL & Fetching it"
        echo "Current working directory: $(pwd)"
        git remote add src https://${{ inputs.git_pat }}@github.com/${{ inputs.github_account_name }}/${{ inputs.src_repo }}.git
        git fetch src
        ls -la  
        git remote -v

    - name: Check if the 2 repos are already in sync or not
      shell: bash
      id: check
      run: |
        set +e
        git checkout ${{ inputs.tgt_branch }}
        git diff --name-status ${{ inputs.tgt_branch }} src/${{ inputs.src_branch }}
        exitcode=$?

        if [ $exitcode -eq 0 ]; then
          echo "skip=true" >> $GITHUB_OUTPUT
        else
          echo "skip=false" >> $GITHUB_OUTPUT
        fi

    - name: Merge SRC branch with CURRENT(TGT) branch
      shell: bash
      if: steps.check.outputs.skip != 'true'
      working-directory: ./temp_repo_dir/${{ inputs.tgt_repo }}
      run: |
        echo "Merging SRC branch with CURRENT(TGT) branch"
        echo "Current working directory: $(pwd)"
        git checkout ${{ inputs.tgt_branch }}
        git merge src/${{ inputs.src_branch }} --allow-unrelated-histories
        ls -la
        git remote -v

    - name: Pushing the changes to the TGT repo
      shell: bash
      if: steps.check.outputs.skip != 'true'
      working-directory: ./temp_repo_dir/${{ inputs.tgt_repo }}
      run: |
        echo "Pushing the changes to the TGT repo"
        echo "Current working directory: $(pwd)"
        git remote -v
        git push -u origin ${{ inputs.tgt_branch }} --force

        