name: "Sync-Cross-Repo" 

on: [workflow_dispatch]
   
jobs:
  sync-repo: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
        with:
          persist-credentials: false  

  
      - uses: aviram2308/my_workflows/actions/sync-repo@master
        name: Calling Sync Action from External Repo
        with: 
          git_pat: ${{ secrets.GIT_PAT }}  
          src_repo: branch_merge
          src_branch: master
          tgt_repo: actions_test
          tgt_branch: master
          github_account_name: aviram2308

